// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9Q67mNvVbvmir1qCjM-aiAF7f2fc1tYU',
    appId: '1:439284288942:web:632172d64921f865360c3f',
    messagingSenderId: '439284288942',
    projectId: 'k8todonote',
    authDomain: 'k8todonote.firebaseapp.com',
    storageBucket: 'k8todonote.appspot.com',
    measurementId: 'G-8Y3KQM8KG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-G4bfL1IsIyglYYibozSwhYw6-pO3pio',
    appId: '1:439284288942:android:54b8da2912db1dd0360c3f',
    messagingSenderId: '439284288942',
    projectId: 'k8todonote',
    storageBucket: 'k8todonote.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7j5JZ29ztN89XBwK_BbKqVpKhkaWJPdE',
    appId: '1:439284288942:ios:f8ad8d2602f2f55c360c3f',
    messagingSenderId: '439284288942',
    projectId: 'k8todonote',
    storageBucket: 'k8todonote.appspot.com',
    iosClientId: '439284288942-s0t2fqlk2poso4006nucqdos7b8bklub.apps.googleusercontent.com',
    iosBundleId: 'com.example.k8todonote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7j5JZ29ztN89XBwK_BbKqVpKhkaWJPdE',
    appId: '1:439284288942:ios:5b6def99ca0228a2360c3f',
    messagingSenderId: '439284288942',
    projectId: 'k8todonote',
    storageBucket: 'k8todonote.appspot.com',
    iosClientId: '439284288942-anad7noigitcdn0tfvojqoh41kegdgq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.k8todonote.RunnerTests',
  );
}
