// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPFqMRHQ-GYwFBuevCnLJZWYdM_lQJwjU',
    appId: '1:820468834359:web:b2bf006710abf4b182dfb2',
    messagingSenderId: '820468834359',
    projectId: 'k8todolistk8',
    authDomain: 'k8todolistk8.firebaseapp.com',
    storageBucket: 'k8todolistk8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI25SlMj9vtqGy0Qvft4H4Va9sWATxRPk',
    appId: '1:820468834359:android:cf2858f58d6edda782dfb2',
    messagingSenderId: '820468834359',
    projectId: 'k8todolistk8',
    storageBucket: 'k8todolistk8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA_mhFq4iRtyz2kyMQbVbTgFxqGSdkxIw',
    appId: '1:820468834359:ios:acd288f780cc716682dfb2',
    messagingSenderId: '820468834359',
    projectId: 'k8todolistk8',
    storageBucket: 'k8todolistk8.appspot.com',
    iosClientId: '820468834359-ccbam0c612rc6to2hd30m5789079vaft.apps.googleusercontent.com',
    iosBundleId: 'com.example.k8todonote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA_mhFq4iRtyz2kyMQbVbTgFxqGSdkxIw',
    appId: '1:820468834359:ios:4d4b70f4ae55801882dfb2',
    messagingSenderId: '820468834359',
    projectId: 'k8todolistk8',
    storageBucket: 'k8todolistk8.appspot.com',
    iosClientId: '820468834359-jv067fsrfnv69v5d7fdnb1hker798o14.apps.googleusercontent.com',
    iosBundleId: 'com.example.k8todonote.RunnerTests',
  );
}
